// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eilleupxcxjpzdepruuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbGxldXB4Y3hqcHpkZXBydXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4ODAwNTYsImV4cCI6MjA4ODQ1NjA1Nn0.GXdhoFZAymuyL2wViyJ_oeIu1P6fC2fB5NZLfpSNjsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});